### ISSUE TITLE
Is this works?

### ISSUE THREAD

**Issue by novayadi85** [vincent2090311/magento2-address#1]
I want made city as dropdown in magento2 checkout..
Is this module work?

**Comment by vincent2090311** [comment]
Yes, the module is working with magento 2.1.x, if you are using magento 2.2.x, you need rename 2 files
app\code\Acommerce\Address\view\base\ui_component\customer_form_22.xml
app\code\Acommerce\Address\view\frontend\templates\address\edit22.phtml

After installed, pls go to admin > customer > import address and use my sample csv in data folder to import. The order to import is region > citi > township (if you dont use township, you can ignore it)

**Comment by novayadi85** [comment]
Thanks, Good work bro..
You save my life
