### ISSUE TITLE
How to Disable Township

### ISSUE THREAD

**Issue by matinict** [vincent2090311/magento2-address#2]
I use this module but i don't need Township ,
Property "Township" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressInterface".

![image](https://user-images.githubusercontent.com/4470372/43773606-13d33e52-9a68-11e8-983d-4f5945f13e07.png)

Using Magento ver. 2.2.3 but need help to solve this issue

**Comment by matinict** [comment]
By The Way If can't help me ,just give me instruction to remove module completely , i disable module but still showing township & City double

**Comment by vincent2090311** [comment]
@matinict 

Here is sql command to remove the module
DELETE FROM eav_attribute WHERE attribute_code = 'city_id';
DELETE FROM eav_attribute WHERE attribute_code = 'township_id';
DELETE FROM eav_attribute WHERE attribute_code = 'township';
DROP TABLE IF EXISTS `directory_region_city`;
DROP TABLE IF EXISTS `directory_region_city_name`;
DROP TABLE IF EXISTS `directory_city_township`;
DROP TABLE IF EXISTS `directory_city_township_name`;
ALTER TABLE customer_address_entity DROP COLUMN city_id;
ALTER TABLE customer_address_entity DROP COLUMN township;
ALTER TABLE customer_address_entity DROP COLUMN township_id;

ALTER TABLE quote_address DROP COLUMN city_id;
ALTER TABLE quote_address DROP COLUMN township;
ALTER TABLE quote_address DROP COLUMN township_id;

ALTER TABLE sales_order_address DROP COLUMN city_id;
ALTER TABLE sales_order_address DROP COLUMN township;
ALTER TABLE sales_order_address DROP COLUMN township_id;

I will add config to enable/disable township on next version

**Comment by matinict** [comment]
@vincent2090311 Thanks for your help, But i think your module very useful some it not working properly magento 2.2.3 , if you get time please updated this module almost all magento store need your module.
