### ISSUE TITLE
How to show the Town in estimate shipping?

### ISSUE THREAD

**Issue by novayadi85** [vincent2090311/magento2-address#3]
How to show the Town in estimate shipping?

**Comment by matinict** [comment]
i also got same problem
//Get $destination
      $city= $this->_checkoutSession->getQuote()->getShippingAddress()->getCity();//working
      $region= $this->_checkoutSession->getQuote()->getShippingAddress()->getRegion();//working 
     $township= $this->_checkoutSession->getQuote()->getShippingAddress()->getTownship();//Not Working

**Comment by matinict** [comment]
at last got point new address field(City_ID,) are not save on  customer_address_entity

**Comment by vincent2090311** [comment]
@novayadi85 
Default magento doesn't use township to estimate shipping so I dont show that field in estimate shipping form
@matinict 
Could you tell me what is your magento version?

**Comment by matinict** [comment]
Thanks for response my magento version 2.2.3

**Comment by vincent2090311** [comment]
@matinict 
I tested on fresh magento 2.2.5 and I can see the data are saved into table customer_address_entity.

**Comment by matinict** [comment]
yes it work for me after disbale Temando_Shipping
