### ISSUE TITLE
address custom field not save?

### ISSUE THREAD

**Issue by matinict** [vincent2090311/magento2-address#5]
customer_address_entity  city_id & township_id value not save but quote_address & sales_order_address       table insert data city_id & township_id field properly  , When new user place order working fine but 2nd worder not placing . Plz check this issue it would be help me.

**Comment by vincent2090311** [comment]
@matinict 
I tested on fresh magento 2.2.5 and I can save 2nd address without any error. pls let me know your step to replicate the issue

**Comment by matinict** [comment]
after   'Temando_Shipping' => 0, work for me
